name: Deploy to Server
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with: 
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.PRIVATE_KEY}}
          command: screen -dm zsh -c "docker-compose down && docker image rm fan-control-fan-control-backend; docker-compose up -d" && exit
